// app/layout.tsx

import type { Metadata } from 'next'
import './globals.css'
import React from 'react'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import BgUi from '@/components/bgUi'

// 1. Import the new official provider
import { WalletContextProvider } from '@/hooks/WalletContextProvider';

export const metadata: Metadata = {
  title: 'GoldFiSolana',
  description: 'Generated by create-solana-dapp',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        {/*
          2. Replace your custom ClusterProvider and WalletProvider
             with the single, official WalletContextProvider.
        */}
        <WalletContextProvider>
            <BgUi>
              <Navbar/>
              {children}
              <Footer/>
            </BgUi>
        </WalletContextProvider>
      </body>
    </html>
  )
}

// You can keep this BigInt patch
declare global {
  interface BigInt {
    toJSON(): string
  }
}

BigInt.prototype.toJSON = function () {
  return this.toString()
}